language: node_js

node_js: "6"

sudo: required

services:
  - docker

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_BRANCH}" >> Dockerfile

install: 
  - npm install
  - docker build -t ${TRAVIS_BRANCH} .

script: 
  - docker run -d --name ${TRAVIS_BRANCH} ${BRANCH}
  - docker ps
