language: node_js

node_js: "6"

sudo: required

services:
  - sshpass

before_install:
  - echo "ENV GIT_SHA ${TRAVIS_BRANCH}" >> Dockerfile

install: 
  - npm install

script: 
  - echo "Hello World"

after_success:
  - tar -czf build.tgz $TRAVIS_BRANCH
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:./
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST
  - cp build.tgz /home/rtanui