language: node_js

node_js: "6"

sudo: required

services:
  - sshpass

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_BRANCH}" >> Dockerfile

install: 
  - npm install

script: 
  - docker images
  - docker run -d --name ${TRAVIS_BRANCH} ${TRAVIS_BRANCH}
  - docker ps

after_success:
  - tar -czf build.tgz $TRAVIS_BRANCH
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:./
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST ./deploy-build.sh
  - docker build -t ${TRAVIS_BRANCH} .