language: node_js

node_js: "6"

sudo: required

services:
  - docker

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_BRANCH}" >> Dockerfile
  - echo $DOCKER_PASSWORD | docker login --username=$DOCKER_USERNAME --password-stdin

install: 
  - npm install

script: 
  - docker images
  
after_success:
  - echo "BUILD IMAGE"
  - docker build -t ${TRAVIS_BRANCH} .
  - docker push $DOCKER_USERNAME/my-hapi/${TRAVIS_BRANCH}:latest
  - docker images