language: node_js

node_js: "6"

sudo: required

services:
  - docker

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile

install: 
  - npm install
  - apt-get install sshpass
  - docker build -t ${TRAVIS_COMMIT} .

script: 
  - docker save ${TRAVIS_COMMIT} | sshpass -p vel94vin ssh -C rtanui@10.50.80.240 sudo docker load