language: node_js

node_js: "6"

sudo: required

services:
  - docker
  - sshpass

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_BRANCH}" >> Dockerfile

install: 
  - npm install
  - docker build -t $TRAVIS_BRANCH .

script: 
  - docker images
  - docker run -d --name $TRAVIS_BRANCH $TRAVIS_BRANCH
  - docker ps
